### ISSUE TITLE
Autoscroll not working for up and down arrow

### ISSUE THREAD

**Issue by Karuturirs** [Canop/whalespotter#1]
Description:
When files and folders are more in any directory and try to move up and down to view with up and down arrow, not able to see the current file on which cursor is when we go down the screen.

Operating system: Mac OS
Steps to replicate the issue: 
1. go to a folder in cmd,  and type whalespotter.
2. move up and down arrow to  see all files not auto scrolling the ui screen in cmd to see current file or folder.(can scroll using mouse but not with arrow keys on keyboard)

**Comment by Canop** [comment]
This is exact. I'll fix this next month (going in holidays tomorrow).
