### ISSUE TITLE
`cargo install` failed with a lot of errors

### ISSUE THREAD

**Issue by drjackild** [Canop/whalespotter#2]
Hi! I'm trying to install whalespotter with `cargo install whalespotter` but it fails with a lot of errors. Here is a gist with output: https://gist.github.com/DrJackilD/93ca976115a18e88da273842f078eaf5

System: Mac OS 10.15.3
rustc: rustc 1.42.0 (b8cedc004 2020-03-09)
cargo: cargo 1.42.0 (86334295e 2020-01-31)

**Comment by Canop** [comment]
This probably happens because
- the cargo.lock file is ignored because you have a different platform
- cargo pick non compatible versions of crossterm and termimad

I'll specify the very precise versions of crossterm and termimad in the cargo.toml file.

**Comment by Canop** [comment]
@DrJackilD Please confirm it's OK for you now

**Comment by drjackild** [comment]
@Canop it works like a charm now, thanks! ☺️
