### ISSUE TITLE
Build Fails on FreeBSD - Outdated Crossterm (Upstream Fixed)

### ISSUE THREAD

**Issue by danieldjewell** [Canop/whalespotter#3]
Hiya,

Whalespotter fails to build on FreeBSD because of an issue (now resolved) in crossterm: https://github.com/crossterm-rs/crossterm/issues/394

Updating the dependency to ```0.14.2``` appears to resolve the issue, per the changelog: https://github.com/crossterm-rs/crossterm/blob/f85105c284ed40d087b991f9250595973ec54fd1/CHANGELOG.md... It compiles and runs as expected as far as I can tell.

Updating to the latest (0.18.2) definitely breaks things but I'm not sure what exactly is broken to suggest a fix...

**Comment by Canop** [comment]
Thanks for the report, I'll have a look ASAP

**Comment by Canop** [comment]
@danieldjewell Can you confirm it's OK for you now ?

If you're interested in whalespotter as a user, you should probably try [broot](https://dystroy.org/broot) which offers way more features, among them the deletion and filesystem information.

Here's what `br --whale-spotting` (`br -w` in short) looks like:

![image](https://user-images.githubusercontent.com/617006/102761306-093b9100-4377-11eb-9536-1ecb58356e4b.png)
