### ISSUE TITLE
Can you port whalespotter to Windows?

### ISSUE THREAD

**Issue by Dhyfer1** [Canop/whalespotter#7]
Hi @Canop 

whalespotter looks very useful, but I don't use linux or Mac. Is it possible that you can create a version for Windows? and if not, do you know any alternative?

Thanks in advance.

**Comment by Canop** [comment]
Hi @Dhyfer1 

You'll find all features of whalespotter in [broot](https://dystroy.org/broot/), when in "whale" mode.

Start broot with `br -w` and you basically have a more powerful whalespotter.

![image](https://github.com/Canop/whalespotter/assets/617006/9fabac95-9766-41fa-8b02-47ebfbfd1138)

**Comment by Dhyfer1** [comment]
Hey, thank you so much. I have started using broot and I like it a lot, before knowing it I used [cdir](https://github.com/EskelinenAntti/cdir) but it's not working anymore, so broot is my favorite and it does a lot of stuff!

By the way, I was having some difficulty knowing how to install and use broot. In the [wiki](https://github.com/Canop/broot/wiki) from the broot repository, the 'Broot for Windows' link in Installation doesn't work, please check it.

I tried various paths on Windows to run Broot, for example C:\Users\username\Downloads\broot.exe, C:\Broot\broot.exe and C:\broot.exe, and I have added these routes to the user's Path environment variable, to make it easier to run the file in PowerShell, but after running the br command an error appeared, but I was able to fix the error by placing broot.exe in the C:\Windows\System32 folder

That's all, in the afternoon I'll show you the error I'm talking about.

Thanks.

**Comment by Canop** [comment]
> In the [wiki](https://github.com/Canop/broot/wiki) from the broot repository, the 'Broot for Windows' link in Installation doesn't work, please check it.

Ahaha... I didn't even know there was a wiki on my project. I'll remove it. The right place for the documentation is https://dystroy.org/broot/install/

**Comment by Dhyfer1** [comment]
Hi again.

Hey, I was checking out the page you mentioned, but the instructions for Windows are scattered in https://dystroy.org/broot/install/ and https://dystroy.org/broot/install-br/ I think you should create a section specifically for Windows showing the steps for installation, in my case I had to do the following:

1. Open PowerShell in Windows Terminal as administrator and enter the following command `set-executionpolicy unrestricted`
2. Still inside PowerShell, go to the path where the executable broot.exe is located with the command `cd C:/executable_path`
3. Enter `broot --install` and let the file do what it has to do in the background
4. When the broot installation is finished, close the shell, in my case Windows Terminal
5. Enter the path to the folder where the executable is located in the Path environment variable (in User or System).
6. Open PowerShell and enter br or broot. At this point broot works as expected.

By the way, I also want to let you know that `broot` cannot be called in Command Prompt of Windows Terminal with `br`, I always have to call it with broot. When I call it with br I get this:
```cmd
C:\Users\diego>br
'br' is not recognized as an internal or external command,
operable program or batch file.
```
Is there any way to solve this? I would also like broot to be able to be called with br in Command Prompt.

**Comment by Canop** [comment]
> By the way, I also want to let you know that broot cannot be called in Command Prompt of Windows Terminal with br

Can you create an issue in the broot repository ? There are Windows users who could maybe help you (I don't have a Windows computer myself so I delegate this part).

**Comment by Dhyfer1** [comment]
Okay, I'll create an issue about broot and command prompt, no problem. 

Since this issue has already been solved then I will close it. Thank you.
